language: c
services:
    - docker
sudo: required
before_install: 
    - make docker-test-build
script:
    - docker run -it -e LIBRARY_PATH="/home/opam/.opam/4.09.0/lib/hack_parallel" -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" comby-local-test-build:latest /bin/bash -c "make && make clean && make build-with-coverage && make test && ./push-coverage-report.sh && ./benchmark"
