language: c
services:
    - docker
sudo: required
before_install: 
    - make docker-test-build
script:
    - docker run -it -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" comby-local-test-build:latest /bin/bash -c "LIBRARY_PATH=/home/opam/.opam/4.09/lib/hack_parallel opam exec -- dune build --profile dev"
